{{- if eq (include "certbot-server.shouldCreateSecret" .) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "certbot-server.secretName" . }}
  labels:
    {{- include "certbot-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
