apiVersion: v1
kind: Service
metadata:
  name: {{ include "pingmailer-raven-sasl.fullname" . }}
  labels:
    {{- include "pingmailer-raven-sasl.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: sasl
      protocol: TCP
      name: sasl
  selector:
    {{- include "pingmailer-raven-sasl.selectorLabels" . | nindent 4 }}
