apiVersion: v1
kind: Service
metadata:
  name: {{ include "silver-smtp.fullname" . }}
  labels:
    {{- include "silver-smtp.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if and (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.service.smtpPort }}
      targetPort: smtp
      protocol: TCP
      name: smtp
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.smtp }}
      nodePort: {{ .Values.service.nodePorts.smtp }}
      {{- end }}
    {{- if .Values.postfix.submission.enabled }}
    - port: {{ .Values.service.submissionPort }}
      targetPort: submission
      protocol: TCP
      name: submission
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.submission }}
      nodePort: {{ .Values.service.nodePorts.submission }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "silver-smtp.selectorLabels" . | nindent 4 }}
